
// This file is auto-generated from the backend's controls.json
// It provides the control data to the frontend for UI elements like dropdowns.

type ControlData = {
  [key: string]: {
    question: string;
  };
};

export const controlsData: ControlData = {
  "AC-1": {
    "question": "Are comprehensive access control policies established that address AI agent authentication, authorization, and accountability requirements?"
  },
  "AC-2": {
    "question": "Do all user accounts and AI agent identities have lifecycle management policies enforced with automated provisioning and deprovisioning?"
  },
  "AC-3": {
    "question": "Are access decisions consistently enforced based on approved authorizations with real-time policy evaluation?"
  },
  "AC-4": {
    "question": "Is information flow between AI agents and external systems controlled according to approved security policies?"
  },
  "AC-6": {
    "question": "Are AI agents and users granted only the minimum privileges necessary for their assigned functions?"
  },
  "AU-1": {
    "question": "Are audit and accountability policies established that address AI agent logging, monitoring, and audit trail protection requirements?"
  },
  "AU-2": {
    "question": "Are all security-relevant events generated by AI agents and system components comprehensively logged with sufficient detail?"
  },
  "IA-1": {
    "question": "Are identification and authentication policies established that address quantum-resistant authentication and AI agent identity management?"
  },
  "IA-2": {
    "question": "Are users and AI agents uniquely identified and authenticated using quantum-resistant cryptographic methods?"
  },
  "SC-12": {
    "question": "Is cryptographic key management implemented with quantum-resistant algorithms and automated lifecycle management?"
  },
  "SI-7": {
    "question": "Is integrity verification implemented for all software and firmware with quantum resistant mechanisms and automated monitoring?"
  },
  "BA-1": {
    "question": "Does the following sequence of user log events contain any suspicious or anomalous behavior when compared to a typical user's baseline activity? A high score (e.g., 90-100) indicates a severe anomaly that requires an immediate alert."
  }
};
